/**
 * inject-pwa.js
 *
 * Post-processes the static web export (dist/index.html) generated by
 * `expo export --platform web` to inject PWA tags (manifest link, theme-color,
 * apple meta tags, and service-worker registration).
 *
 * Run AFTER `expo export --platform web`:
 *   node scripts/inject-pwa.js
 */

const fs = require("fs");
const path = require("path");

const DIST = path.resolve(__dirname, "..", "dist");
const INDEX = path.join(DIST, "index.html");

if (!fs.existsSync(INDEX)) {
  console.error(
    `[inject-pwa] dist/index.html not found.\n` +
    `Run "expo export --platform web" first.`
  );
  process.exit(1);
}

let html = fs.readFileSync(INDEX, "utf-8");

// ── HEAD injections ──────────────────────────────────────────────────────────
const HEAD_TAGS = `
  <!-- PWA manifest & meta (injected by inject-pwa.js) -->
  <link rel="manifest" href="/manifest.json" />
  <meta name="theme-color" content="#1a1a1a" />
  <meta name="mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
  <meta name="apple-mobile-web-app-title" content="PluralNest" />
  <link rel="apple-touch-icon" href="/icon.png" />
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon.png" />`;

// ── Body injection: service-worker registration ──────────────────────────────
const SW_SCRIPT = `
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', function () {
        navigator.serviceWorker
          .register('/sw.js', { scope: '/' })
          .catch(function (err) {
            console.warn('[PluralNest] Service worker registration failed:', err);
          });
      });
    }
  </script>`;

// Inject HEAD_TAGS just before </head>
if (html.includes("</head>")) {
  html = html.replace("</head>", `${HEAD_TAGS}\n</head>`);
} else {
  console.warn("[inject-pwa] Could not find </head> — manifest link NOT injected.");
}

// Inject SW script just before </body>
if (html.includes("</body>")) {
  html = html.replace("</body>", `${SW_SCRIPT}\n</body>`);
} else {
  console.warn("[inject-pwa] Could not find </body> — SW registration NOT injected.");
}

fs.writeFileSync(INDEX, html, "utf-8");

// ── Copy public/ assets to dist/ ────────────────────────────────────────────
const PUBLIC = path.resolve(__dirname, "..", "public");
if (fs.existsSync(PUBLIC)) {
  const files = fs.readdirSync(PUBLIC);
  for (const file of files) {
    const src = path.join(PUBLIC, file);
    const dest = path.join(DIST, file);
    if (fs.statSync(src).isFile()) {
      fs.copyFileSync(src, dest);
      console.log(`[inject-pwa] Copied public/${file} → dist/${file}`);
    }
  }
}

console.log("[inject-pwa] Done — dist/index.html updated for PWA.");
