const colors = {
  light: {
    text: "#1a1a1a",
    tint: "#7c6fcd",
    background: "#f5f5f5",
    foreground: "#1a1a1a",
    card: "#ffffff",
    cardForeground: "#1a1a1a",
    primary: "#7c6fcd",
    primaryForeground: "#ffffff",
    secondary: "#e8e8e8",
    secondaryForeground: "#1a1a1a",
    muted: "#e8e8e8",
    mutedForeground: "#888888",
    accent: "#7c6fcd",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e0e0e0",
    input: "#e0e0e0",
  },
  dark: {
    text: "#f0f0f0",
    tint: "#aaaaaa",
    background: "#252525",
    foreground: "#f0f0f0",
    card: "#303030",
    cardForeground: "#f0f0f0",
    primary: "#aaaaaa",
    primaryForeground: "#ffffff",
    secondary: "#3d3d3d",
    secondaryForeground: "#f0f0f0",
    muted: "#3d3d3d",
    mutedForeground: "#b0b0b0",
    accent: "#aaaaaa",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#3a3a3a",
    input: "#3a3a3a",
  },
  radius: 12,
};

export default colors;
